#include <stdio.h>
#include "template.h"

SellerData* searchSellersTree(SellerTree* sellerNode, unsigned int sellerID) {
  SellerData* retval=NULL;
  if(sellerNode->is_leaf) {
    int i=0;
    while(i<sellerNode->numKeys && sellerID>sellerNode->sellerdata[i].sellerID) i++;
    if(i<sellerNode->numKeys && sellerNode->sellerdata[i].sellerID == sellerID) retval=&sellerNode->sellerdata[i];
  }
  else {
    int i=0;
    while(i<sellerNode->numKeys && sellerID>=sellerNode->sellerdata[i].sellerID) i++;
    retval=searchSellersTree(sellerNode->children[i],sellerID);
  }
  return retval;
}

void calculateRevenue(SellerTree* sellerRoot) {
  printf("[!] Warning: If you have added any entry in the database or not made the set of transactions for sellers, the expected results may not be shown!\nIn case of which you might need to consider creating a the set by pressing 3.\n\n");
  unsigned int sellerID;
  printf("Enter the seller ID: "); scanf("%u",&sellerID);
  SellerData* target=searchSellersTree(sellerRoot,sellerID);
  float revenue=0.0;
  
  if(target) {
    TransactionTree* subtransRoot=target->subtree;
    while(!subtransRoot->is_leaf) subtransRoot=subtransRoot->children[0];

    while(subtransRoot) {
      for(int j=0;j<subtransRoot->numKeys;j++) 
        revenue+=subtransRoot->data.trans[j].total_price;
      
      subtransRoot=subtransRoot->next;
    }

    printf("The revenue generated by Seller %u is %.2f\n",sellerID,revenue);
  }
  else printf("Given Seller ID does not exist!!\n");
}
